"""Character option lists for forms and generation."""
from .catalog import ALIGNMENTS, BODY_TYPES, CHARACTER_TAGS, DND_BACKGROUNDS, DND_RACES, EMOTION_STYLES, GENDERS, IMAGE_STYLES, MAGIC_TYPES, POWER_SYSTEMS, PROFESSIONS, QUIRKS_LIST, SKILLS_LIST, TRAITS_LIST, WEAPON_TYPES
