#!/usr/bin/env python3
"""
Ark_Ai - one-shot installer.

Cross-platform replacement for install.bat / install_ark_ai.bat: creates a
virtual environment, installs dependencies, initializes the database, writes
a local .env, and creates desktop shortcuts - on Windows this includes BOTH
the regular Desktop and the OneDrive-synced Desktop (if OneDrive is set up),
so the launcher icon shows up wherever the user actually looks for it.

Usage:
    python full_install.py [--dev] [--postgres DATABASE_URL] [--network]

Safe to re-run: every step is idempotent (skips work that's already done).
"""
import argparse
import os
import secrets
import shutil
import subprocess
import sys
import venv

APP_DIR = os.path.dirname(os.path.abspath(__file__))
VENV_DIR = os.path.join(APP_DIR, "venv")
ENV_PATH = os.path.join(APP_DIR, ".env")
ICON_PATH = os.path.join(APP_DIR, "relay.ico")
IS_WINDOWS = sys.platform.startswith("win")


def venv_python():
    if IS_WINDOWS:
        return os.path.join(VENV_DIR, "Scripts", "python.exe")
    return os.path.join(VENV_DIR, "bin", "python3")


def step(msg):
    print("\n==> " + msg)


def run(cmd, **kw):
    print("    $ " + " ".join(cmd))
    subprocess.run(cmd, check=True, **kw)


def create_venv():
    step("Setting up virtual environment")
    if os.path.exists(venv_python()):
        print("    Already exists - skipping.")
        return
    venv.EnvBuilder(with_pip=True).create(VENV_DIR)
    print("    Created at " + VENV_DIR)


def install_requirements(dev, postgres):
    step("Installing dependencies")
    py = venv_python()
    run([py, "-m", "pip", "install", "--upgrade", "pip"])
    run([py, "-m", "pip", "install", "-r", os.path.join(APP_DIR, "requirements.txt")])
    if dev:
        dev_req = os.path.join(APP_DIR, "requirements-dev.txt")
        if os.path.exists(dev_req):
            run([py, "-m", "pip", "install", "-r", dev_req])
    if postgres:
        pg_req = os.path.join(APP_DIR, "requirements-postgres.txt")
        if os.path.exists(pg_req):
            run([py, "-m", "pip", "install", "-r", pg_req])


def write_env(network, postgres):
    step("Writing .env")
    if os.path.exists(ENV_PATH):
        print("    .env already exists - leaving it untouched.")
        return
    secret_key = secrets.token_hex(32)
    host = "0.0.0.0" if network else "127.0.0.1"
    lines = [
        "# Ark_Ai local configuration - generated by full_install.py",
        "# This file is gitignored and must never be committed.",
        "ARK_AI_SECRET_KEY=" + secret_key,
        "ARK_AI_HOST=" + host,
        "ARK_AI_PORT=5000",
    ]
    if network:
        token = secrets.token_hex(24)
        lines.append("ARK_AI_TOKEN=" + token)
        print("    Generated ARK_AI_TOKEN: " + token)
    if postgres:
        lines.append("DATABASE_URL=" + postgres)
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("    Wrote " + ENV_PATH)


def init_db(postgres):
    step("Initializing database")
    env = os.environ.copy()
    if postgres:
        env["DATABASE_URL"] = postgres
    run([venv_python(), "-c", "import db; db.init_db(); print('Database ready at:', db.DATABASE_URL or db.DB_PATH)"],
        cwd=APP_DIR, env=env)


def onedrive_desktop_roots():
    """Every OneDrive Desktop folder actually present on this machine.
    Windows stores the real synced path in OneDrive/OneDriveCommercial env
    vars - it isn't always %USERPROFILE%\\OneDrive, and a work/school account
    names it "OneDrive - <Company>"."""
    roots = []
    for var in ("OneDriveCommercial", "OneDrive"):
        val = os.environ.get(var)
        if val:
            roots.append(val)
    userprofile = os.environ.get("USERPROFILE")
    if userprofile:
        roots.append(os.path.join(userprofile, "OneDrive"))
    seen, out = set(), []
    for root in roots:
        desktop = os.path.join(root, "Desktop")
        if desktop not in seen and os.path.isdir(desktop):
            seen.add(desktop)
            out.append(desktop)
    return out


def normal_desktop():
    userprofile = os.environ.get("USERPROFILE")
    if userprofile:
        return os.path.join(userprofile, "Desktop")
    return os.path.join(os.path.expanduser("~"), "Desktop")


def create_windows_shortcut(path):
    """Write a .lnk via PowerShell + WScript.Shell (no extra Python deps)."""
    target = os.path.join(APP_DIR, "venv", "Scripts", "pythonw.exe")
    script = os.path.join(APP_DIR, "app.py")
    ps = (
        "$s=(New-Object -ComObject WScript.Shell).CreateShortcut('{path}');"
        "$s.TargetPath='{target}';"
        "$s.Arguments='\"{script}\"';"
        "$s.WorkingDirectory='{cwd}';"
        "$s.Description='Ark_Ai - personal AI workspace';"
        "{icon}"
        "$s.Save();"
    ).format(
        path=path.replace("'", "''"),
        target=target.replace("'", "''"),
        script=script.replace("'", "''"),
        cwd=APP_DIR.replace("'", "''"),
        icon=("$s.IconLocation='%s';" % ICON_PATH.replace("'", "''")) if os.path.exists(ICON_PATH) else "",
    )
    subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps], check=True)


def create_linux_desktop_entry(path):
    target = os.path.join(APP_DIR, "venv", "bin", "python3")
    script = os.path.join(APP_DIR, "app.py")
    content = (
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=Ark_Ai\n"
        "Comment=Ark_Ai - personal AI workspace\n"
        "Exec=\"{target}\" \"{script}\"\n"
        "Path={cwd}\n"
        "Icon={icon}\n"
        "Terminal=false\n"
    ).format(target=target, script=script, cwd=APP_DIR, icon=ICON_PATH if os.path.exists(ICON_PATH) else "")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    os.chmod(path, 0o755)


def create_macos_shortcut(path):
    """A double-clickable .command launcher (macOS has no native .lnk)."""
    target = os.path.join(APP_DIR, "venv", "bin", "python3")
    script = os.path.join(APP_DIR, "app.py")
    content = "#!/bin/bash\ncd \"%s\"\n\"%s\" \"%s\"\n" % (APP_DIR, target, script)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    os.chmod(path, 0o755)


def create_shortcuts():
    step("Creating desktop shortcuts")
    if IS_WINDOWS:
        targets = onedrive_desktop_roots()
        normal = normal_desktop()
        if normal not in targets:
            targets.append(normal)
        if not targets:
            targets = [normal]
        for desktop_dir in targets:
            try:
                os.makedirs(desktop_dir, exist_ok=True)
                lnk = os.path.join(desktop_dir, "Ark_Ai.lnk")
                create_windows_shortcut(lnk)
                print("    Created: " + lnk)
            except Exception as e:
                print("    WARNING: could not create shortcut in %s (%s)" % (desktop_dir, e))
        # Start Menu, for parity with install_ark_ai.bat
        appdata = os.environ.get("APPDATA")
        if appdata:
            start_menu = os.path.join(appdata, "Microsoft", "Windows", "Start Menu", "Programs")
            try:
                os.makedirs(start_menu, exist_ok=True)
                lnk = os.path.join(start_menu, "Ark_Ai.lnk")
                create_windows_shortcut(lnk)
                print("    Created: " + lnk)
            except Exception as e:
                print("    WARNING: could not create Start Menu shortcut (%s)" % e)
    elif sys.platform == "darwin":
        desktop_dir = os.path.join(os.path.expanduser("~"), "Desktop")
        try:
            os.makedirs(desktop_dir, exist_ok=True)
            path = os.path.join(desktop_dir, "Ark_Ai.command")
            create_macos_shortcut(path)
            print("    Created: " + path)
        except Exception as e:
            print("    WARNING: could not create Desktop shortcut (%s)" % e)
    else:
        desktop_dir = os.path.join(os.path.expanduser("~"), "Desktop")
        try:
            os.makedirs(desktop_dir, exist_ok=True)
            path = os.path.join(desktop_dir, "Ark_Ai.desktop")
            create_linux_desktop_entry(path)
            print("    Created: " + path)
        except Exception as e:
            print("    WARNING: could not create Desktop shortcut (%s)" % e)


def main():
    parser = argparse.ArgumentParser(description="Ark_Ai installer")
    parser.add_argument("--dev", action="store_true", help="also install requirements-dev.txt")
    parser.add_argument("--postgres", metavar="DATABASE_URL", default="",
                         help="use PostgreSQL instead of the default SQLite file")
    parser.add_argument("--network", action="store_true",
                         help="bind to 0.0.0.0 instead of 127.0.0.1 and generate an ARK_AI_TOKEN")
    parser.add_argument("--no-shortcuts", action="store_true", help="skip desktop shortcut creation")
    args = parser.parse_args()

    if not os.path.exists(os.path.join(APP_DIR, "app.py")):
        sys.exit("ERROR: app.py not found - run this from inside the Ark_Ai project folder.")

    print("=" * 60)
    print("  Ark_Ai - installer")
    print("=" * 60)
    print("Installing into: " + APP_DIR)

    create_venv()
    install_requirements(args.dev, args.postgres)
    write_env(args.network, args.postgres)
    init_db(args.postgres)
    if not args.no_shortcuts:
        create_shortcuts()

    step("Install complete")
    print("Run Ark_Ai any time with:")
    if IS_WINDOWS:
        print("    venv\\Scripts\\python.exe app.py")
    else:
        print("    venv/bin/python3 app.py")
    print("or double-click the Ark_Ai shortcut on your Desktop"
          + (" / OneDrive Desktop / Start Menu" if IS_WINDOWS else "") + ".")
    print("URL: http://127.0.0.1:5000" if not args.network else "URL: http://0.0.0.0:5000")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as e:
        sys.exit("ERROR: command failed (%s)" % e)
    except KeyboardInterrupt:
        sys.exit("\nCancelled.")
